spring:
  data:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace