spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  data:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace