spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
      host: localhost
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
